import { breadcrumbs, hero, linkButton } from '../templates/site.mjs';

const infoStart = (label, path) => breadcrumbs([{ label: 'Inicio', path: '' }, { label, path }]);
const card = (title, text, path, label = 'Abrir herramienta') => `<article class="card"><h2>${title}</h2><p>${text}</p>${linkButton(path, label)}</article>`;

const panSide = (side, label, defaults) => `<fieldset class="pan-side" data-side="${side}"><legend>${label}</legend>
  <label>Forma<select name="${side}-shape"><option value="round"${defaults.shape === 'round' ? ' selected' : ''}>Redondo</option><option value="square">Cuadrado</option><option value="rectangle">Rectangular</option></select></label>
  <div data-shape="round"><label>Diámetro interior <span>cm</span><input name="${side}-diameter" value="${defaults.diameter || 20}" inputmode="decimal"></label></div>
  <div data-shape="square"><label>Lado interior <span>cm</span><input name="${side}-side" value="20" inputmode="decimal"></label></div>
  <div data-shape="rectangle"><label>Ancho interior <span>cm</span><input name="${side}-width" value="20" inputmode="decimal"></label><label>Largo interior <span>cm</span><input name="${side}-length" value="30" inputmode="decimal"></label></div>
  <label>Altura de masa deseada <span>cm</span><input name="${side}-height" value="4" inputmode="decimal"></label>
  <label>Número de moldes<input name="${side}-count" value="1" inputmode="numeric"></label>
</fieldset>`;

export const pages = [
  {
    path: '', title: 'HornoExacto: adapta recetas y moldes con cálculos claros', h1: 'Tu receta, ajustada al molde y a la cantidad que necesitas',
    description: 'Calculadoras gratuitas para adaptar una receta a otro molde, cambiar cantidades y trabajar con porcentaje panadero.',
    schema: { '@context': 'https://schema.org', '@type': 'WebSite', name: 'HornoExacto', url: 'https://elvaropablo-oss.github.io/horno-exacto/', inLanguage: 'es-ES' },
    content: `${hero('Calculadoras de repostería y pan', 'Tu receta, ajustada al molde y a la cantidad que necesitas', 'Introduce tus medidas o ingredientes y revisa el factor antes de aplicarlo. Todo se calcula en tu navegador, sin crear una cuenta.', `${linkButton('adaptar-molde/', 'Tengo otro molde')}${linkButton('escalar-receta/', 'Quiero otra cantidad', true)}`)}
      <section class="section"><div class="section-heading"><h2>Empieza por el dato que ya conoces</h2><p>Molde, cantidad o fórmula: cada recorrido conserva el cálculo para el siguiente paso.</p></div><div class="card-grid">
      ${card('Adaptar un molde', 'Compara la capacidad ocupada de moldes redondos, cuadrados o rectangulares y obtén un factor explícito.', 'adaptar-molde/')}
      ${card('Escalar ingredientes', 'Cambia porciones, aplica un factor de molde o fija la cantidad de un ingrediente.', 'escalar-receta/')}
      ${card('Porcentaje panadero', 'Calcula pesos desde la harina o desde una masa total y reparte la masa en piezas.', 'porcentaje-panadero/')}
      </div></section>
      <section class="section split"><div><h2>Del molde a una ficha que puedes guardar</h2><ol class="steps"><li>Mide el interior y decide cuánto quieres llenar.</li><li>Aplica el factor a una tabla editable de ingredientes.</li><li>Guarda o imprime el escenario desde tu dispositivo.</li></ol></div><aside class="sample-card"><p class="metric-label">Ejemplo matemático</p><p>Molde redondo de 20 cm → 24 cm</p><p class="big-number">× 1,44</p><p>250 g pasan a 360 g. El tiempo y la temperatura no se multiplican.</p></aside></section>
      <section class="section trust"><h2>Qué calcula y qué no</h2><p>HornoExacto aplica geometría y proporciones. No promete que recetas distintas se comporten igual ni prescribe horneado, fermentación o seguridad alimentaria. Puedes consultar las fórmulas y límites en la <a href="/horno-exacto/metodologia/">metodología</a>.</p></section>`
  },
  {
    path: 'herramientas', title: 'Calculadoras de recetas y moldes | HornoExacto', h1: 'Herramientas de HornoExacto',
    description: 'Directorio de calculadoras para adaptar moldes, escalar ingredientes y calcular porcentajes panaderos.',
    content: `${infoStart('Herramientas', 'herramientas/')} ${hero('Directorio', 'Herramientas de HornoExacto', 'Cada calculadora funciona por separado y puede guardar un resultado en Mi receta.')}
      <section class="section card-grid">${card('Adaptar receta a otro molde', 'Calcula por área, altura de masa y número de recipientes.', 'adaptar-molde/')}${card('Escalar una receta', 'Aumenta o reduce una tabla de ingredientes con un único criterio visible.', 'escalar-receta/')}${card('Porcentaje panadero', 'Trabaja con harina total, hidratación y masa por pieza.', 'porcentaje-panadero/')}</section>`
  },
  {
    path: 'adaptar-molde', tool: 'pan', title: 'Adaptar receta a otro molde: calculadora | HornoExacto', h1: 'Calculadora para adaptar una receta a otro molde',
    description: 'Calcula el factor para cambiar una receta entre moldes redondos, cuadrados o rectangulares según sus medidas interiores.',
    content: `${infoStart('Adaptar molde', 'adaptar-molde/')} ${hero('Geometría del molde', 'Calculadora para adaptar una receta a otro molde', 'Compara el volumen de masa que quieres ocupar. El factor se puede enviar directamente al escalador de ingredientes.')}
      <section class="tool-layout"><form id="pan-form" class="tool-card" novalidate>${panSide('origin', 'Molde de la receta', { shape: 'round', diameter: 20 })}${panSide('destination', 'Molde que vas a usar', { shape: 'round', diameter: 24 })}<div id="form-error" class="error" role="alert" tabindex="-1" hidden></div><button class="button" type="submit">Calcular factor</button></form><section id="pan-result" class="result-card" tabindex="-1" aria-live="polite" hidden></section></section>
      <section class="section prose"><h2>Cómo se obtiene el factor</h2><p>En un molde redondo usamos π × diámetro² ÷ 4. En uno cuadrado, lado²; en uno rectangular, ancho × largo. Multiplicamos por la altura de masa deseada y el número de moldes. La relación entre destino y origen es el factor.</p><h2>Limitaciones que importan</h2><p>Introduce la altura que ocupará la masa, no toda la altura del recipiente. Esta versión no calcula moldes con hueco, paredes inclinadas ni formas decorativas. El cambio de grosor y forma afecta al horneado de una manera que la geometría por sí sola no puede resolver.</p><p>${linkButton('guias/medir-moldes/', 'Cómo medir un molde', true)}</p></section>`
  },
  {
    path: 'escalar-receta', tool: 'scale', title: 'Escalar una receta y sus ingredientes | HornoExacto', h1: 'Escala todos los ingredientes de una receta',
    description: 'Cambia las porciones, aplica un factor de molde o fija una cantidad objetivo sin convertir unidades incompatibles.',
    content: `${infoStart('Escalar receta', 'escalar-receta/')} ${hero('Regla de tres controlada', 'Escala todos los ingredientes de una receta', 'Elige un solo criterio. La tabla original permanece visible y el resultado muestra el factor aplicado.')}
      <section class="tool-layout"><form id="scale-form" class="tool-card" novalidate><fieldset><legend>1. Cómo quieres escalar</legend><label class="radio"><input type="radio" name="factor-mode" value="factor" checked> Usar un factor</label><label class="radio"><input type="radio" name="factor-mode" value="servings"> Cambiar porciones</label><label class="radio"><input type="radio" name="factor-mode" value="target"> Fijar un ingrediente</label><div data-factor-fields="factor"><label>Factor<input name="factor" value="1,5" inputmode="decimal"></label></div><div data-factor-fields="servings" hidden><label>Porciones originales<input name="source-servings" value="4" inputmode="decimal"></label><label>Porciones finales<input name="target-servings" value="6" inputmode="decimal"></label></div><div data-factor-fields="target" hidden><label>Número de fila del ingrediente (empieza en 1)<input name="target-index" value="1" inputmode="numeric"></label><label>Cantidad final deseada<input name="target-quantity" value="500" inputmode="decimal"></label></div></fieldset>
      <fieldset><legend>2. Ingredientes</legend><label>Pegar ingredientes, uno por línea<textarea id="ingredient-paste" rows="4" placeholder="250 g harina&#10;1/2 cucharadita sal"></textarea></label><button type="button" class="button button--quiet" id="parse-ingredients">Importar líneas reconocibles</button><p id="parse-feedback" class="field-note" aria-live="polite">Formato: cantidad, unidad y nombre. Las líneas dudosas no se adivinan.</p><div id="ingredient-rows"></div><div class="inline-actions"><button type="button" class="button button--quiet" id="add-ingredient">Añadir ingrediente</button><button type="button" class="button button--quiet" id="load-scale-example">Cargar ejemplo</button></div></fieldset><div id="form-error" class="error" role="alert" tabindex="-1" hidden></div><button class="button" type="submit">Escalar y guardar</button></form><section id="scale-result" class="result-card" tabindex="-1" aria-live="polite" hidden></section></section>
      <section class="section prose"><h2>Qué ocurre con huevos y unidades</h2><p>Una cantidad discreta puede quedar en 1,44 huevos. La herramienta no redondea en secreto: puedes batir y pesar el huevo si tu receta lo permite. Multiplicamos gramos, mililitros, tazas o cucharadas dentro de su propia unidad; no convertimos volumen en masa sin una densidad comprobada.</p><p>${linkButton('guias/escalar-sin-errores/', 'Evitar errores al escalar', true)}</p></section>`
  },
  {
    path: 'porcentaje-panadero', tool: 'baker', title: 'Calculadora de porcentaje panadero e hidratación | HornoExacto', h1: 'Calculadora de porcentaje panadero',
    description: 'Calcula ingredientes desde la harina o desde una masa total, con hidratación y masa por pieza.',
    content: `${infoStart('Porcentaje panadero', 'porcentaje-panadero/')} ${hero('Harina = 100 %', 'Calculadora de porcentaje panadero', 'Convierte una fórmula en gramos y reparte la masa. Esta versión no incluye prefermentos ni masa madre.')}
      <section class="tool-layout"><form id="baker-form" class="tool-card" novalidate><fieldset><legend>1. Punto de partida</legend><label class="radio"><input type="radio" name="baker-mode" value="flour" checked> Sé cuánta harina usaré y los porcentajes</label><label class="radio"><input type="radio" name="baker-mode" value="total"> Sé la masa total que quiero</label><label class="radio"><input type="radio" name="baker-mode" value="weights"> Conozco todos los pesos</label><label id="total-mass-field" hidden>Masa total <span>g</span><input name="total-mass" value="1680" inputmode="decimal"></label><p class="field-note">Al cambiar de modo, revisa las cifras: las etiquetas indican si cada campo espera gramos o porcentajes.</p></fieldset><fieldset><legend>2. Harinas</legend><div id="flour-rows"></div><button type="button" class="button button--quiet" id="add-flour">Añadir harina</button></fieldset><fieldset><legend>3. Otros ingredientes</legend><div id="baker-ingredient-rows"></div><button type="button" class="button button--quiet" id="add-baker-ingredient">Añadir ingrediente</button></fieldset><label>Número de piezas<input name="pieces" value="4" inputmode="numeric"></label><div id="form-error" class="error" role="alert" tabindex="-1" hidden></div><button class="button" type="submit">Calcular y guardar</button></form><section id="baker-result" class="result-card" tabindex="-1" aria-live="polite" hidden></section></section>
      <section class="section prose"><h2>La fórmula</h2><p>La suma de todas las harinas representa el 100 %. Cada ingrediente se expresa respecto a ese peso. Si partes de una masa total, la harina es masa total ÷ (1 + suma de porcentajes distintos de harina ÷ 100).</p><h2>Un límite deliberado</h2><p>Los prefermentos y la masa madre contienen harina y agua que deben contabilizarse dentro de los totales. Quedan fuera de esta primera versión para no ofrecer una hidratación engañosa.</p></section>`
  },
  {
    path: 'mi-receta', tool: 'project', noindex: true, title: 'Mi receta guardada | HornoExacto', h1: 'Mi receta', description: 'Consulta y exporta el último cálculo guardado en este dispositivo.',
    content: `${infoStart('Mi receta', 'mi-receta/')} ${hero('Guardado local', 'Mi receta', 'El último escenario se guarda únicamente en este navegador. No se sincroniza entre dispositivos.')}
      <section class="section"><div id="project-empty" class="empty-state"><h2>Todavía no hay una receta guardada</h2><p>Calcula una receta o una fórmula panadera para verla aquí.</p>${linkButton('herramientas/', 'Elegir una herramienta')}</div><div id="project-view" class="result-card" hidden></div><div class="import-card"><h2>Importar una copia</h2><p>Selecciona un JSON exportado por HornoExacto. Se valida antes de reemplazar el proyecto local.</p><input id="project-import-file" type="file" accept="application/json,.json" hidden><button id="project-import" type="button" class="button button--quiet">Elegir archivo JSON</button><p id="project-import-feedback" class="error" role="alert" hidden></p></div></section>
      <section class="section prose"><h2>Privacidad y copias</h2><p>Exporta el archivo JSON si quieres conservar una copia. Borrar datos de navegación también puede eliminar este proyecto. Una URL compartida no contiene la receta completa.</p></section>`
  },
  {
    path: 'guias/medir-moldes', title: 'Cómo medir un molde para adaptar una receta | HornoExacto', h1: 'Cómo medir el molde antes de adaptar una receta', description: 'Aprende qué dimensiones interiores utilizar y por qué la altura ocupada por la masa importa.',
    content: `${infoStart('Cómo medir moldes', 'guias/medir-moldes/')} ${hero('Guía práctica', 'Cómo medir el molde antes de adaptar una receta', 'Una medición coherente evita aplicar un factor correcto a dimensiones equivocadas.')}
      <article class="section prose"><h2>Mide el espacio que ocupa la masa</h2><ol><li>Usa dimensiones interiores, sin contar el borde exterior.</li><li>En redondos mide el diámetro pasando por el centro.</li><li>En rectangulares mide ancho y largo en el interior.</li><li>Anota la altura aproximada que la masa ocupa antes de hornear.</li></ol><h2>Cuándo no usar la equivalencia</h2><p>Los moldes con tubo central, paredes inclinadas o cavidades decorativas no se describen bien con las tres formas disponibles. Tampoco conviene trasladar el factor entre preparaciones diferentes.</p><p>${linkButton('adaptar-molde/', 'Abrir calculadora')}</p></article>`
  },
  {
    path: 'guias/escalar-sin-errores', title: 'Cómo escalar una receta sin errores | HornoExacto', h1: 'Cómo escalar una receta sin mezclar criterios', description: 'Usa un único factor, revisa unidades y conserva visibles las cantidades originales.',
    content: `${infoStart('Escalar sin errores', 'guias/escalar-sin-errores/')} ${hero('Guía de cantidades', 'Cómo escalar una receta sin mezclar criterios', 'El error más común es aplicar dos veces el mismo cambio o convertir unidades incompatibles.')}
      <article class="section prose"><h2>Elige una sola referencia</h2><p>Usa porciones, factor de molde o cantidad objetivo. Si vienes de la calculadora de moldes, ese factor ya contiene el cambio geométrico.</p><h2>Revisa cantidades discretas</h2><p>Huevos, sobres o piezas pueden producir fracciones. HornoExacto las enseña; tú decides cómo medirlas según la receta.</p><h2>No confundas gramos y mililitros</h2><p>Son masa y volumen. Solo pueden convertirse mediante una densidad específica y fiable, que esta versión no presupone.</p><p>${linkButton('escalar-receta/', 'Escalar ingredientes')}</p></article>`
  },
  {
    path: 'metodologia', title: 'Metodología, fórmulas y límites | HornoExacto', h1: 'Metodología y límites de cálculo', description: 'Consulta las fórmulas geométricas, de escalado y de porcentaje panadero utilizadas por HornoExacto.',
    content: `${infoStart('Metodología', 'metodologia/')} ${hero('Cálculos transparentes', 'Metodología y límites de cálculo', 'Publicamos las fórmulas, ejemplos y exclusiones para que puedas revisar el resultado.')}
      <article class="section prose"><h2>Molde</h2><p>Área circular = πd²/4; cuadrada = lado²; rectangular = ancho × largo. Factor = (número destino × área destino × altura de masa destino) ÷ (número origen × área origen × altura de masa origen).</p><h2>Ingredientes</h2><p>Cantidad nueva = cantidad original × factor. El resultado conserva la unidad.</p><h2>Porcentaje panadero</h2><p>Cada ingrediente = harina total × porcentaje ÷ 100. Desde una masa total: harina = masa total ÷ (1 + suma de porcentajes no harineros ÷ 100).</p><h2>Fuentes y alcance</h2><p>La convención de porcentaje panadero está documentada por <a href="https://www.kingarthurbaking.com/pro/reference/bakers-percentage" rel="external">King Arthur Baking</a>. Las áreas son geometría elemental. Estas operaciones no predicen tiempo, temperatura, fermentación ni seguridad alimentaria.</p></article>`
  },
  {
    path: 'sobre', title: 'Sobre HornoExacto', h1: 'Sobre HornoExacto', description: 'HornoExacto es un experimento gratuito de herramientas transparentes para adaptar recetas.',
    content: `${infoStart('Sobre', 'sobre/')} ${hero('Proyecto abierto y pequeño', 'Sobre HornoExacto', 'Una web gratuita para hacer visibles las proporciones que suelen acabar en una nota o una calculadora.')}
      <article class="section prose"><h2>Principios</h2><p>La herramienta se centra en cálculos justificables, contenido original y una experiencia rápida en móvil. No publica recetas copiadas ni recomendaciones de cocción que no pueda sostener.</p><h2>Estado</h2><p>Esta es una primera versión experimental. La utilidad técnica no demuestra demanda de mercado; las mejoras se decidirán a partir de problemas observados y datos reales.</p></article>`
  },
  {
    path: 'privacidad', title: 'Privacidad | HornoExacto', h1: 'Privacidad', description: 'Cómo trata HornoExacto los datos de recetas y el almacenamiento local.',
    content: `${infoStart('Privacidad', 'privacidad/')} ${hero('Datos en tu dispositivo', 'Privacidad', 'Las calculadoras funcionan en el navegador y no necesitan una cuenta.')}
      <article class="section prose"><h2>Recetas y cálculos</h2><p>El proyecto se guarda mediante almacenamiento local del navegador bajo claves propias de HornoExacto. No se envía a un servidor. Puedes borrarlo desde Mi receta o limpiando los datos del sitio.</p><h2>Analítica</h2><p>Google Analytics solo se activa si aceptas la analítica opcional. La elección se guarda en este navegador; si rechazas, el almacenamiento de analítica permanece desactivado. Google puede tratar datos técnicos de navegación conforme a su propia política de privacidad.</p><h2>Limitaciones</h2><p>El almacenamiento local puede desaparecer al borrar datos y no sincroniza dispositivos. No guardes información sensible.</p></article>`
  },
  {
    path: '404', output: '404.html', noindex: true, title: 'Página no encontrada | HornoExacto', h1: 'Página no encontrada', description: 'La página solicitada no existe.',
    content: `${hero('Error 404', 'Página no encontrada', 'La dirección puede haber cambiado o contener un error.', linkButton('', 'Volver al inicio'))}`
  }
];
